name: Ideas
description: Have a new idea/feature for EddieBot?
title: "[FEATURE] <description>"
labels: ["⭐ goal: addition"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Feel free to check out other cool repositories [here](https://github.com/ankushsinghgandhi)
